export default {
  MARK_NOTIFICATION_BY_ID: "MARK_NOTIFICATION_BY_ID",
  MARK_ALL_NOTIFICATION: "MARK_ALL_NOTIFICATION",
  START_MARK: "START_MARK",//开始发送请求
  FINSH_MARK: "FINSH_MARK", // 请求完成
  RECEIVE_NOTIFICATION: "RECEIVE_NOTIFICATION", //接收第一次的渲染数据
  /**
   * 登录的action一般都是有下面这三个action组成的
   */
  LOGIN_START: "LOGIN_START", //开始登录
  LOGIN_SUCCESS: "LOGIN_SUCCESS", // 登录成功
  LOGIN_FAIL: "LOGIN_FAIL", //登录失败
  CHANGE_AVATAR: "CHANGE_AVATAR", // 更改头像
}