export default {
  MARK_NOTIFICATION_BY_ID: "MARK_NOTIFICATION_BY_ID",
  MARK_ALL_NOTIFICATION: "MARK_ALL_NOTIFICATION",
  START_MARK: "START_MARK",//开始发送请求
  FINSH_MARK: "FINSH_MARK", // 请求完成
  RECEIVE_NOTIFICATION: "RECEIVE_NOTIFICATION", //接收第一次的渲染数据
}